### PR TITLE
Migration to ES6 modules

### PR DESCRIPTION
**Pull request by jpsullivan**
So here's a mammoth of a PR... I'm going to explain a bit of what this does, but to summarize, here's a nice list.

- `npm run build` now generates a (near) complete bundle of Higher, including minified builds for distribution. For more info, see the Known Issues section.
- Each component is now an ES6 module, emitting everything needed to use a single function directly, as well as the registration context needed to use Higher the "old-fashioned way".
- Paves the way to make unit testing clean and simple as individual functions can be tested in isolation.
- A demo server is now available when running `npm run start` which monitors the source files for changes, hot reloading the page after each save.
- When running `npm run start`, Webpack will alert when compilation errors are detected due to missing or otherwise invalid dependencies.

## Notable Changes

**Function Registration**

Function registration no longer occurs within the Function itself. Each Function now emits a *registration object export*. This object itself should look somewhat familiar, but the core difference is that registration evaluation is deferred until the entry point manually performs the Function registration.
```javascript
// src/functions/concat.js
export const registration = {
    name: "concat",
    expected: {
        sequences: "*",
    },
    implementation: concat, // concat defined elsewhere
};
```
```javascript
// src/higher.js
import {registration as concat} from "./functions/concat";
...
hi.register(concat);
```
This allows Higher to preserve it's core functionality while allowing us and other developers to manually pull down the *Function implementation itself*.
```javascript
// src/functions/some-new-module.js
import map from "./map";
...
return map(transform, sequences);
```
Note that the `map()` call no longer requires `hi.map.raw()`.

This also gives us the ability to build a dependency map of the library, allowing developers to code-split Higher and, depending on their use case, reduce its total bundle size tremendously.

**Aliasing**

Previously, aliasing a Function required a call like `hi.alias("forEach", "each");`. This has been changed to accomodate the registration object export. If a user wanted to alias a Function, they would now do so within the export itself.
```javascript
export const registration = {
    name: "each",
    aliases: ["forEach"],
    expected: {
        ...
    },
    implementation: each,
};
```
The alias functionality is now directly integrated into the root `register()` method.

**Demo Server**

Running `npm run start` will spin up a temporary server at http://localhost:3000 so that your changes can be tested on the fly. Right now this loads up a static page with a fancy little splash image to show that things are indeed working, but this can be greatly expanded on to essentially make a test bed for common functionality.

When the demo server is running, Webpack will continue to run in watch mode, monitoring changes to the file system. Make a change to any imported module, and the page will automatically reload.

## Known Issues

- ~~A circular dependency exists between `empty` and `repeat`, where each relies on a sequence constructor that is defined in the other module. To allow compilation to pass, each `import` is commented out.~~
- ~~`OnceSequence` seems to be missing, causing `flatten` to error out~~
- ~~`sequenceBoundsError` is missing, causing `write` to error out~~
- `hi.Promise()` and `hi.callAsync()` usage is still preserved as I feel that is something we can look into together.

## Next Steps

I think that from here, I'll be taking some time to get a stable test framework put in place. Even though I tested each change that was made, huge changes like this terrify me without tests. I believe that having them going forward would be greatly beneficial.

While this PR checks a lot of boxes to getting Higher ready for a proper 1.0 build, there are definitely a whole bunch of ways that this can be cleaned up even further.

And as always, I'm open to suggestions/thoughts/concerns if you have any to offer!

### CODE REVIEW

**Comment by pineapplemachine** [comment]
Ok, wall of text incoming.

### Blockers

Users generally should not be calling `hi.map.raw`. They should call the `fancy` wrapper function returned by invoking `hi.wrap`, [defined in `src/core/wrappers.js`](https://github.com/pineapplemachine/higher/blob/master/src/core/wrappers.js#L15). The wrapper function is important because it includes argument validation logic. Modules must export a wrapped function (and, in the handful of cases where the function currently is not wrapped, this probably should be changed (though this will require some small changes to function wrapping logic... I'll get to this soon)) and the implementation should continue to be accessible via `raw` or a similar attribute.

For my sake, I must be able to rapidly test changes and additions with a repl. I currently do this with an HTML file that loads all the JavaScript. It looks like this is probably possible by doing the same with the served webpage? If so then I think we're good. If not this needs to be changed before the PR is merged.

### Per known issues

I'll push fixes for the first three of these this morning.

As well as other changes/additions I made yesterday but didn't push yet including:

- Adding a few more things along the lines of `hi.Promise` and `hi.callAsync` - i.e. the default comparison etc. functions that are used when none was specified.

- Trivial improvement to `hi.Sequence.prototype.unbounded` in `sequence.js`.

- Trivial improvement to `concat.js`.

- `reverse` support for the sequence returned by `flatten` in `flatten.js`.

- Right pad functionality in `pad.js`.

- Added `split.js` and `join.js`.

I think the last three points will imply some additional changes in your branch, I think the first three won't?

### Good stuff

I like putting the aliases in the registration object, and I can get with the idea of a separate registration object in general.

How would this be for an improved pattern? `wrap` should return a `fancy` function with the registration object and other wrapped functions attached to it.

``` js
export const each = wrap({
    names: ["each", "forEach"],
    expected: {},
    implementation: function(...){...},
});

export const forEach = each;

// Return value looks like:

each(sequence, callback); // Is callable
each.names // Names
each.implementation // Refers to implementation
each.expected // Duh
each.async // Async fancy wrapper
each.method // Sequence prototype method (to be attached to the prototype at some point)
each.method.async // Async prototype method wrapper
```

**Comment by pineapplemachine** [comment]
> A circular dependency exists between empty and repeat, where each relies on a sequence constructor that is defined in the other module. To allow compilation to pass, each import is commented out.

Fixed in https://github.com/pineapplemachine/higher/commit/a8b471db004e28f4675d10c2bb07977f946cc1e7

> OnceSequence seems to be missing, causing flatten to error out

Fixed in https://github.com/pineapplemachine/higher/commit/5442e9bd0503996482beb60e5c5c8996b8467c6c

> sequenceBoundsError is missing, causing write to error out

Fixed in https://github.com/pineapplemachine/higher/commit/2ab44dedc78731db1e4e18b63604856892c1b5ed

**Comment by jpsullivan** [comment]
Thanks for the quick feedback. I know we spoke earlier but I wanted to formally include an update here. 

I went ahead and merged the upstream changes so conflict-wise, we should be good.This also takes care of nearly all of the "known issues" both you and I had mentioned.

> Users generally should not be calling hi.map.raw. They should call the fancy wrapper function returned by invoking hi.wrap, defined in src/core/wrappers.js. The wrapper function is important because it includes argument validation logic.

I must admit I wasn't aware of this when I was putting things together. Fortunately that shouldn't really affect us. For Functions internal to Higher, it's still important to pull down the implementation of a Function so that things stay context-free.

> For my sake, I must be able to rapidly test changes and additions with a repl. I currently do this with an HTML file that loads all the JavaScript. It looks like this is probably possible by doing the same with the served webpage? If so then I think we're good. If not this needs to be changed before the PR is merged.

That's correct, when running `npm run start`, webpack is sending a complete, albeit unminified bundle of higher across that is pre-loaded onto the page. Simply open the developer tools console and you're good to go.

> How would this be for an improved pattern? wrap should return a fancy function with the registration object and other wrapped functions attached to it.

Looks good to me! Would you prefer I include those changes with this PR or should that occur elsewhere?

**Comment by pineapplemachine** [comment]
> Looks good to me! Would you prefer I include those changes with this PR or should that occur elsewhere?

As discussed - I'm currently working in a branch that I'll make a PR for merging into yours before we merge this into master. This is looking pretty good but I want to further improve the pattern for defining/wrapping/registering functions in modules before committing fully to this approach.

That branch is here: https://github.com/pineapplemachine/higher/tree/es6-conversion-more

**Comment by jpsullivan** [comment]
I'm pretty happy with this! There's other things we can still do to strengthen the codebase, but right now this is a fantastic start. I'm gonna let you give this another once-over to ensure that this is in a good state to merge.

I've got some ideas to make testing work the way you had envisioned, so I'll be spending a bit of time on that over the next few days or so.

**Pull request merged**
